# $XDG_CONFIG_HOME may be not set here on WSL Ubuntu
. "$HOME/.local/etc/sh/config"
. "$XDG_CONFIG_HOME/sh/interactive"

if [[ -d "$XDG_CONFIG_HOME/bash/bashrc.d" ]]; then
	for script in "$XDG_CONFIG_HOME/bash/bashrc.d/"*.zsh; do
		if [[ -r "$script" ]]; then
			. $script
		fi
		unset script
	done
fi
