WEAKLINE_CONTEXT_BACKGROUND=black
WEAKLINE_CONTEXT_FOREGROUND=227

function weakline_context() {
	weakline_write_segment "$USER@${(C)HOST}" $WEAKLINE_CONTEXT_BACKGROUND $WEAKLINE_CONTEXT_FOREGROUND
}
