WEAKLINE_INDICATOR_BACKGROUND=white
WEAKLINE_INDICATOR_FOREGROUND=black
WEAKLINE_INDICATOR_ROOT_BACKGROUND=yellow
WEAKLINE_INDICATOR_ROOT_FOREGROUND=black

function weakline_indicator() {
	if [[ $UID == 0 ]]; then
		if [[ $TERM == "xterm-256color" ]]; then
			weakline_write_segment "\uE1E5" $WEAKLINE_INDICATOR_ROOT_BACKGROUND $WEAKLINE_INDICATOR_ROOT_FOREGROUND
		else
			weakline_write_segment "#" $WEAKLINE_INDICATOR_ROOT_BACKGROUND $WEAKLINE_INDICATOR_ROOT_FOREGROUND
		fi
	else
		weakline_write_segment "%(!,#,$)" $WEAKLINE_INDICATOR_BACKGROUND $WEAKLINE_INDICATOR_FOREGROUND
	fi
}
