WEAKLINE_RETVAL_ERROR_BACKGROUND=red
WEAKLINE_RETVAL_ERROR_FOREGROUND=yellow

function weakline_retval() {
	if [[ $WEAKLINE_RETVAL != 0 ]]; then
		weakline_write_segment "$WEAKLINE_RETVAL" $WEAKLINE_RETVAL_ERROR_BACKGROUND $WEAKLINE_RETVAL_ERROR_FOREGROUND;
	fi
}
