bindkey '\e[1~' beginning-of-line
bindkey '\eOH' beginning-of-line
bindkey '\e[H' beginning-of-line
bindkey '\e[4~' end-of-line
bindkey '\eOF' end-of-line
bindkey '\e[F' end-of-line
bindkey '\e[A' history-substring-search-up
bindkey '\e[B' history-substring-search-down
bindkey '\e[2~' overwrite-mode
bindkey '\e[3~' delete-char
bindkey '\e[5~' beginning-of-buffer-or-history
bindkey '\e[6~' end-of-buffer-or-history
bindkey '\e' kill-whole-line
